### ISSUE TITLE
login button is invisible on Android 4.0.4

### ISSUE THREAD

**Issue by danielamorais** [slidenerd/FaceBookv4.0HelloWorld#1]
I tested on a real smartphone, Xperia U Android 4.0.4 and is only displayed a gray screen with the application title without any buttons. <b>I've changed the id of the app in fb_app_id.xml.</b> <br>Does anyone have any idea why this happens?

**Comment by mooniub428** [comment]
check this tutorial
https://www.youtube.com/watch?v=myWu-q8Q2NA
